import { Listing, User } from '../types';

export const MOCK_USERS: User[] = [
  { 
    id: 'u1', 
    username: 'ProSeller_X', 
    role: 'user', 
    avatarUrl: 'https://picsum.photos/seed/u1/100/100',
    isVerified: true,
    premiumStatus: 'approved',
    password: 'password123',
    email: 'proseller@nexus.com',
    bio: 'Elite trader since 2020. Specializing in high-tier bundles.',
    joinedAt: new Date(Date.now() - 31536000000).toISOString()
  },
  { 
    id: 'u2', 
    username: 'NewbieTrader', 
    role: 'user', 
    avatarUrl: 'https://picsum.photos/seed/u2/100/100',
    isVerified: false,
    premiumStatus: 'pending',
    password: 'password123',
    email: 'newbie@nexus.com',
    bio: 'Just started trading.',
    joinedAt: new Date(Date.now() - 10000000).toISOString()
  },
  { 
    id: 'admin1', 
    username: 'NexusAdmin', 
    role: 'admin', 
    avatarUrl: 'https://picsum.photos/seed/admin1/100/100',
    isVerified: true,
    premiumStatus: 'approved',
    password: 'admin',
    email: 'admin@nexus.market',
    bio: 'System Administrator. Keeping the marketplace secure.',
    joinedAt: new Date(Date.now() - 63072000000).toISOString()
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    ownerId: 'u1',
    title: 'SAKURA S1 + HIP HOP | FULL MAX EVO',
    level: 82,
    likes: 15400,
    region: 'NA',
    loginMethod: 'Facebook',
    price: 450,
    status: 'available',
    accountAge: '4 Years',
    primeLevel: 'Max',
    vaultCount: 650,
    bundles: ['Sakura Bundle', 'Hip Hop Bundle', 'Criminal Red', 'Arctic Blue'],
    evoGuns: ['AK47 Blue Flame (Max)', 'MP40 Cobra (Max)', 'Scar Megalodon (Lvl 6)'],
    elitePasses: ['S1', 'S2', 'S3', 'S4', 'S5', 'S10-S20'],
    rarityTags: ['Old School', 'Whale', 'Tournament Ready'],
    gunVaultCount: 420,
    dressVaultCount: 850,
    glooWallCount: 45,
    emotesCount: 120,
    animationCount: 15,
    highlights: [
      'Top 100 Regional Badge',
      'Full Incubator Collection',
      'Clean Bindings'
    ],
    contactUsername: '@ProSeller_X',
    proofLink: '#',
    paymentMethods: ['Binance', 'Wise'],
    images: ['https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80'],
    featured: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'l2',
    ownerId: 'u1',
    title: 'LVL 70 | 3 EVO MAX | GOOD STARTER',
    level: 70,
    likes: 5200,
    region: 'EU',
    loginMethod: 'Google',
    price: 120,
    status: 'available',
    accountAge: '2 Years',
    primeLevel: 'None',
    vaultCount: 200,
    bundles: ['Green Criminal', 'Dino Bundle'],
    evoGuns: ['MP40 Cobra (Max)', 'M1014 Green (Lvl 5)'],
    elitePasses: ['S20+'],
    rarityTags: ['Budget King'],
    gunVaultCount: 150,
    dressVaultCount: 300,
    glooWallCount: 15,
    emotesCount: 40,
    animationCount: 2,
    highlights: [
      'Cheap Price',
      'Full Access',
      'No Hack History'
    ],
    contactUsername: '@ProSeller_X',
    proofLink: '#',
    paymentMethods: ['PayPal'],
    images: [],
    featured: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
   {
    id: 'l3',
    ownerId: 'u1',
    title: 'GRANDMASTER ID | 90% WR',
    level: 91,
    likes: 99999,
    region: 'BR',
    loginMethod: 'VK',
    price: 1200,
    status: 'reserved',
    accountAge: '5 Years',
    primeLevel: 'Ultimate',
    vaultCount: 1200,
    bundles: ['All Elite Pass', 'All Incubator', 'Developer Shirt'],
    evoGuns: ['ALL EVO GUNS MAX'],
    elitePasses: ['All Seasons'],
    rarityTags: ['God Tier', 'Streamer Account'],
    gunVaultCount: 900,
    dressVaultCount: 2000,
    glooWallCount: 150,
    emotesCount: 200,
    animationCount: 50,
    highlights: [
      'Verified Influencer Badge',
      'Top 1 Global S24',
      'Rare ID Number'
    ],
    contactUsername: '@NexusAdmin',
    proofLink: '#',
    paymentMethods: ['Crypto Only'],
    images: ['https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=800&q=80'],
    featured: true,
    createdAt: new Date(Date.now() - 400000).toISOString(),
    updatedAt: new Date(Date.now() - 400000).toISOString(),
  }
];